const ADMIN_EMAIL='aryamangupta55@gmail.com';
const CHANNEL='https://whatsapp.com/channel/0029VbCvdFAKgsNqcyZiRL3k';
const enc=new TextEncoder();
const hex=b=>Array.from(new Uint8Array(b),x=>x.toString(16).padStart(2,'0')).join('');
const random=(n=32)=>hex(crypto.getRandomValues(new Uint8Array(n)));
const hash=async s=>hex(await crypto.subtle.digest('SHA-256',enc.encode(s)));
async function passwordHash(password,salt){const key=await crypto.subtle.importKey('raw',enc.encode(password),'PBKDF2',false,['deriveBits']);return hex(await crypto.subtle.deriveBits({name:'PBKDF2',salt:enc.encode(salt),iterations:100000,hash:'SHA-256'},key,256));}
function same(a,b){if(typeof a!=='string'||typeof b!=='string'||a.length!==b.length)return false;let n=0;for(let i=0;i<a.length;i++)n|=a.charCodeAt(i)^b.charCodeAt(i);return n===0;}
function fail(message,status=400){throw Object.assign(new Error(message),{status});}
function text(v,max=200,min=0){if(typeof v!=='string'||v.trim().length<min||v.length>max)fail('Please check the required fields.');return v.trim();}
function email(v){const s=text(v,254,3).toLowerCase();if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(s))fail('Enter a valid email address.');return s;}
function password(v){if(typeof v!=='string'||v.length<10||v.length>128)fail('Use a password with 10–128 characters.');return v;}
function obj(v){if(!v||typeof v!=='object'||Array.isArray(v))fail('Invalid data.');return v;}
const now=()=>new Date().toISOString();
function json(data,status=200,headers={}){return new Response(JSON.stringify(data),{status,headers:{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store','X-Content-Type-Options':'nosniff',...headers}});}
const run=(db,sql,...args)=>db.prepare(sql).bind(...args).run();
const first=(db,sql,...args)=>db.prepare(sql).bind(...args).first();
const all=async(db,sql,...args)=>(await db.prepare(sql).bind(...args).all()).results;
function publicUser(u){return{id:u.id,email:u.email,name:u.name,role:u.role,created_at:u.created_at,last_login:u.last_login,login_count:u.login_count};}
async function rate(db,key,limit,seconds){const time=Math.floor(Date.now()/1000),r=await first(db,'INSERT INTO rate_limits(key,count,expires_at) VALUES (?,1,?) ON CONFLICT(key) DO UPDATE SET count=CASE WHEN expires_at<? THEN 1 ELSE count+1 END, expires_at=CASE WHEN expires_at<? THEN excluded.expires_at ELSE expires_at END RETURNING count',key,time+seconds,time,time);if(r.count>limit)fail('Too many attempts. Please wait and try again.',429);}
async function session(request,db){const match=(request.headers.get('cookie')||'').match(/(?:^|;\s*)campus_session=([a-f0-9]{64})(?:;|$)/);if(!match)return null;return first(db,'SELECT users.* FROM sessions JOIN users ON users.id=sessions.user_id WHERE token_hash=? AND expires_at>?',await hash(match[1]),Date.now());}
async function loginResponse(user,db,request,extra={}){const token=random(),stamp=now(),expiry=Date.now()+7*86400000;await db.batch([db.prepare('INSERT INTO sessions(token_hash,user_id,expires_at) VALUES (?,?,?)').bind(await hash(token),user.id,expiry),db.prepare('UPDATE users SET last_login=?,login_count=login_count+1 WHERE id=?').bind(stamp,user.id),db.prepare('INSERT INTO login_events(id,user_id,created_at) VALUES (?,?,?)').bind(crypto.randomUUID(),user.id,stamp)]);await run(db,'DELETE FROM sessions WHERE expires_at<?',Date.now());const cookie=`campus_session=${token}; Path=/; HttpOnly; SameSite=Lax; Max-Age=604800${new URL(request.url).protocol==='https:'?'; Secure':''}`;return json({user:publicUser({...user,last_login:stamp,login_count:user.login_count+1}),...extra},200,{'Set-Cookie':cookie});}
function urlSafe(value){if(!value)return '';try{const u=new URL(value);if(u.protocol!=='https:'||u.username||u.password)throw Error();return u.href;}catch{fail('Links must use HTTPS.');}}
function cleanData(input){const d=obj(input),profile=obj(d.profile||{}),safe={};safe.course=d.course===null?null:text(d.course||'',80);safe.profile={name:text(profile.name||'',80),goal:text(profile.goal||'',150),skills:text(profile.skills||'',500),about:text(profile.about||'',1500),github:urlSafe(profile.github||'')};
for(const key of ['projects','updates','expenses']){if(!Array.isArray(d[key]||[])||(d[key]||[]).length>500)fail('Too many records.');}
safe.projects=(d.projects||[]).map(p=>({id:text(p.id,100,1),title:text(p.title,120,1),description:text(p.description,1500),contribution:text(p.contribution,1500),skills:text(p.skills||'',500),status:['In progress','Completed'].includes(p.status)?p.status:'In progress',repo:urlSafe(p.repo||''),demo:urlSafe(p.demo||'')}));
safe.updates=(d.updates||[]).filter(u=>safe.projects.some(p=>p.id===u.project)).map(u=>({id:text(u.id,100,1),project:text(u.project,100,1),text:text(u.text,1500,1),link:urlSafe(u.link||''),date:text(u.date||'',80)}));
function money(n){if(!Number.isSafeInteger(n)||n<0||n>10000000000)fail('Enter a valid amount.');return n;}
safe.budget=money(d.budget||0);safe.expenses=(d.expenses||[]).map(e=>({id:text(e.id,100,1),name:text(e.name,150,1),category:text(e.category,80,1),amount:money(e.amount)}));safe.goal={name:text(d.goal?.name||'',150),target:money(d.goal?.target||0),saved:money(d.goal?.saved||0)};safe.progress={};for(const [key,steps]of Object.entries(obj(d.progress||{}))){if(Object.keys(safe.progress).length>100)fail('Too many course records.');if(!Array.isArray(steps))fail('Invalid roadmap.');safe.progress[text(key,80,1)]=[...new Set(steps.filter(n=>Number.isInteger(n)&&n>=0&&n<50))];}
if(d.resume!==undefined){const r=obj(d.resume),sections=['summary','education','experience','projects','skills','certifications','achievements'];safe.resume={};for(const [key,max] of Object.entries({name:80,role:150,email:254,phone:40,location:150,linkedin:1500,github:1500,website:1500,summary:2500,skills:1500,achievements:2500}))safe.resume[key]=text(r[key]||'',max);
const fields={education:{institution:180,degree:180,period:180,details:2500},experience:{company:180,title:180,period:180,details:2500},projects:{title:180,tech:180,link:1500,details:2500},certifications:{title:180,issuer:180,period:180,link:1500}};
for(const [key,columns]of Object.entries(fields)){if(!Array.isArray(r[key]||[])||(r[key]||[]).length>12)fail('Use up to 12 entries per résumé section.');safe.resume[key]=(r[key]||[]).map(entry=>{obj(entry);return Object.fromEntries(Object.entries(columns).map(([k,max])=>[k,text(entry[k]||'',max)]));});}
for(const key of ['order','hidden'])if(r[key]!==undefined&&!Array.isArray(r[key]))fail('Invalid résumé layout.');safe.resume.order=[...new Set([...(r.order||[]).filter(k=>sections.includes(k)),...sections])];safe.resume.hidden=[...new Set((r.hidden||[]).filter(k=>sections.includes(k)))];}
if(d.career!==undefined){const c=obj(d.career);safe.career={role:text(c.role||'',80),level:c.level==='Know some basics'?'Know some basics':'Beginner',language:['All','Hindi','English'].includes(c.language)?c.language:'All',progress:{}};const entries=Object.entries(obj(c.progress||{}));if(entries.length>50)fail('Too many career paths.');for(const [key,steps]of entries){if(!Array.isArray(steps)||steps.length>50)fail('Invalid career progress.');if(!/^[a-z0-9-]{1,80}$/.test(key))fail('Invalid career role.');safe.career.progress[key]=[...new Set(steps.map(v=>text(v,80,1)))];}}
return safe;}
async function requestList(db,user){const rows=await all(db,`SELECT r.*,u.name,u.email FROM requests r JOIN users u ON u.id=r.user_id ${user.role==='admin'?'':'WHERE r.user_id=?'} ORDER BY r.created_at DESC LIMIT 500`,...(user.role==='admin'?[]:[user.id]));for(const r of rows){r.messages=await all(db,'SELECT m.id,m.body AS text,m.created_at,u.role,u.name FROM messages m JOIN users u ON u.id=m.user_id WHERE m.request_id=? ORDER BY m.created_at',r.id);r.files=await all(db,'SELECT id,name,size,mime FROM attachments WHERE request_id=?',r.id);}return rows;}
async function body(request){if(Number(request.headers.get('content-length')||0)>200000)fail('This request is too large.',413);let raw=await request.text();if(raw.length>200000)fail('This request is too large.',413);try{return obj(JSON.parse(raw));}catch(e){if(e.status)throw e;fail('Invalid request.');}}
export async function handleApi(request,env){try{const db=env.DB;if(!db)fail('Database is not connected yet.',503);const path=new URL(request.url).pathname.replace(/^\/api/,'')||'/',method=request.method;
if(!['GET','HEAD'].includes(method)){const origin=request.headers.get('origin');if(origin!==new URL(request.url).origin||request.headers.get('X-Campus-Request')!=='1')fail('Request origin not allowed.',403);}
if(path==='/health')return json({ok:true,database:!!await first(db,'SELECT 1 AS ready')});
if(path==='/content'&&method==='GET'){const rows=await all(db,'SELECT id,kind,data FROM content');const config=await first(db,"SELECT data FROM settings WHERE id='campus'");return json({items:rows.map(r=>({...JSON.parse(r.data),id:r.id,kind:r.kind})),settings:config?JSON.parse(config.data):{channel:CHANNEL,support:'Free personal guidance for student projects, presentations, technical questions, and budget planning.'}});}
if(path.startsWith('/share/')&&method==='GET'){const id=path.split('/')[2];const row=await first(db,'SELECT d.data FROM shared_portfolios s JOIN user_data d ON d.user_id=s.user_id WHERE s.token=?',id);if(!row)fail('This portfolio is private or no longer shared.',404);const d=JSON.parse(row.data);return json({profile:d.profile,course:d.course,projects:d.projects,updates:d.updates});}
if(['/auth/signup','/auth/login','/auth/recover'].includes(path)&&method==='POST'){const b=await body(request),mail=email(b.email),ip=request.headers.get('cf-connecting-ip')||env.LOCAL_IP||'local';await rate(db,'auth-ip:'+await hash(ip),180,900);await rate(db,'auth-email:'+await hash(mail),12,900);const existing=await first(db,'SELECT * FROM users WHERE email=?',mail);
if(path==='/auth/signup'){const name=text(b.name,80,1),pass=password(b.password);if(existing)fail('This account cannot be created. Try logging in or recovering your account.',409);let role='student';if(mail===ADMIN_EMAIL){const verified=env.TRUST_SITES_AUTH===true&&request.headers.get('oai-authenticated-user-email')?.toLowerCase()===ADMIN_EMAIL;const setup=env.ADMIN_SETUP_TOKEN&&same(await hash(String(b.adminCode||'')),await hash(env.ADMIN_SETUP_TOKEN));if(!verified&&!setup)fail('This address is reserved for the owner. Enter your private admin setup code.',403);role='admin';}const salt=random(16),recovery=random(20),u={id:crypto.randomUUID(),email:mail,name,role,created_at:now(),last_login:null,login_count:0};const statement=db.prepare('INSERT INTO users(id,email,name,password_hash,salt,recovery_hash,role,created_at,login_count) VALUES (?,?,?,?,?,?,?,?,0)').bind(u.id,mail,name,await passwordHash(pass,salt),salt,await hash(recovery),role,u.created_at);try{await db.batch([statement,db.prepare('INSERT INTO user_data(user_id,data,version,updated_at) VALUES (?,?,0,?)').bind(u.id,JSON.stringify({profile:{name}}),now())]);}catch{fail('This account could not be created. Try logging in.',409);}return loginResponse(u,db,request,{recoveryCode:recovery});}
if(path==='/auth/login'){const pass=password(b.password),salt=existing?.salt||'00000000000000000000000000000000',computed=await passwordHash(pass,salt);if(!existing||!same(computed,existing.password_hash))fail('Email or password is incorrect.',401);return loginResponse(existing,db,request);}
if(path==='/auth/recover'){const pass=password(b.password),code=text(b.recoveryCode,100,1);if(!existing||!same(await hash(code),existing.recovery_hash))fail('Email or recovery code is incorrect.',401);const salt=random(16),recovery=random(20);await db.batch([db.prepare('UPDATE users SET password_hash=?,salt=?,recovery_hash=? WHERE id=?').bind(await passwordHash(pass,salt),salt,await hash(recovery),existing.id),db.prepare('DELETE FROM sessions WHERE user_id=?').bind(existing.id)]);return loginResponse(existing,db,request,{recoveryCode:recovery});}}
const user=await session(request,db);if(path==='/me'&&method==='GET')return json({user:user?publicUser(user):null,adminVerified:env.TRUST_SITES_AUTH===true&&request.headers.get('oai-authenticated-user-email')?.toLowerCase()===ADMIN_EMAIL});if(!user)fail('Please log in to continue.',401);
if(path==='/auth/logout'&&method==='POST'){const token=(request.headers.get('cookie')||'').match(/campus_session=([a-f0-9]{64})/)?.[1];if(token)await run(db,'DELETE FROM sessions WHERE token_hash=?',await hash(token));return json({ok:true},200,{'Set-Cookie':'campus_session=; Path=/; HttpOnly; SameSite=Lax; Max-Age=0; Secure'});}
if(path==='/auth/password'&&method==='POST'){const b=await body(request);if(!same(await passwordHash(password(b.current),user.salt),user.password_hash))fail('Current password is incorrect.',401);const salt=random(16),recovery=random(20);await db.batch([db.prepare('UPDATE users SET password_hash=?,salt=?,recovery_hash=? WHERE id=?').bind(await passwordHash(password(b.password),salt),salt,await hash(recovery),user.id),db.prepare('DELETE FROM sessions WHERE user_id=?').bind(user.id)]);return loginResponse(user,db,request,{recoveryCode:recovery});}
if(path==='/state'&&method==='GET'){const row=await first(db,'SELECT data,version FROM user_data WHERE user_id=?',user.id),shared=await first(db,'SELECT token FROM shared_portfolios WHERE user_id=?',user.id);return json({data:JSON.parse(row?.data||'{}'),version:row?.version||0,shareToken:shared?.token||null});}
if(path==='/state'&&method==='PUT'){const b=await body(request),data=cleanData(b.data);const prior=await first(db,'SELECT data FROM user_data WHERE user_id=?',user.id);const priorData=JSON.parse(prior?.data||'{}');for(const key of ['resume','career'])if(data[key]===undefined&&priorData[key]!==undefined)data[key]=priorData[key];if(!Number.isInteger(b.version))fail('Invalid save version.');const r=await first(db,'UPDATE user_data SET data=?,version=version+1,updated_at=? WHERE user_id=? AND version=? RETURNING version',JSON.stringify(data),now(),user.id,b.version);if(!r)fail('Your data changed in another tab. Reload before editing again.',409);if(data.profile.name)await run(db,'UPDATE users SET name=? WHERE id=?',data.profile.name,user.id);return json({version:r.version});}
if(path==='/portfolio/share'&&method==='POST'){const b=await body(request);if(b.enabled){const token=random(24);await run(db,'INSERT INTO shared_portfolios(token,user_id,created_at) VALUES (?,?,?) ON CONFLICT(user_id) DO UPDATE SET token=excluded.token,created_at=excluded.created_at',token,user.id,now());return json({token});}await run(db,'DELETE FROM shared_portfolios WHERE user_id=?',user.id);return json({token:null});}
if(path==='/requests'&&method==='GET')return json({requests:await requestList(db,user)});
if(path==='/requests'&&method==='POST'){await rate(db,'requests:'+user.id,20,3600);if(Number(request.headers.get('content-length')||0)>26*1024*1024)fail('Files are too large.',413);const form=await request.formData(),description=text(form.get('description'),2500,15),category=text(form.get('category'),100,1),timing=text(form.get('timing'),100,1);const files=form.getAll('files').filter(f=>typeof f!=='string'&&f.size);if(files.length>5||files.some(f=>f.size>1024*1024))fail('Attach up to 5 files, no more than 1 MB each.');const accepted={pdf:'application/pdf',png:'image/png',jpg:'image/jpeg',jpeg:'image/jpeg',webp:'image/webp',txt:'text/plain',docx:'application/vnd.openxmlformats-officedocument.wordprocessingml.document',xlsx:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'};for(const f of files)if(!accepted[f.name.split('.').pop().toLowerCase()])fail('Use PDF, PNG, JPG, WebP, TXT, DOCX, or XLSX files.');if(files.length&&!env.BUCKET)fail('File storage is unavailable. Submit without files or try later.',503);const id=crypto.randomUUID(),stamp=now(),uploaded=[];try{for(const f of files){const fid=crypto.randomUUID(),key=user.id+'/'+id+'/'+fid;await env.BUCKET.put(key,await f.arrayBuffer());uploaded.push({id:fid,key,name:f.name.replace(/[\x00-\x1f/\\]/g,'_').slice(0,150),size:f.size,mime:accepted[f.name.split('.').pop().toLowerCase()]});}await db.batch([db.prepare('INSERT INTO requests(id,user_id,category,description,timing,created_at,updated_at) VALUES (?,?,?,?,?,?,?)').bind(id,user.id,category,description,timing,stamp,stamp),...uploaded.map(f=>db.prepare('INSERT INTO attachments(id,request_id,name,size,mime,object_key) VALUES (?,?,?,?,?,?)').bind(f.id,id,f.name,f.size,f.mime,f.key))]);}catch(e){await Promise.all(uploaded.map(f=>env.BUCKET.delete(f.key)));throw e;}return json({id},201);}
if(path.startsWith('/files/')&&method==='GET'){const f=await first(db,'SELECT a.*,r.user_id FROM attachments a JOIN requests r ON r.id=a.request_id WHERE a.id=?',path.split('/')[2]);if(!f||(user.role!=='admin'&&f.user_id!==user.id))fail('File not found.',404);const stored=await env.BUCKET?.get(f.object_key);if(!stored)fail('File not found.',404);return new Response(stored.body,{headers:{'Content-Type':'application/octet-stream','Content-Disposition':`attachment; filename*=UTF-8''${encodeURIComponent(f.name)}`,'Cache-Control':'private, no-store','X-Content-Type-Options':'nosniff','Content-Security-Policy':"default-src 'none'; sandbox"}});}
if(path.match(/^\/requests\/[^/]+\/reply$/)&&method==='POST'){const id=path.split('/')[2],r=await first(db,'SELECT * FROM requests WHERE id=?',id);if(!r||(user.role!=='admin'&&r.user_id!==user.id))fail('Request not found.',404);await rate(db,'replies:'+user.id,60,3600);const b=await body(request);await db.batch([db.prepare('INSERT INTO messages(id,request_id,user_id,body,created_at) VALUES (?,?,?,?,?)').bind(crypto.randomUUID(),id,user.id,text(b.text,1500,1),now()),db.prepare('UPDATE requests SET status=?,updated_at=? WHERE id=?').bind(user.role==='admin'?'In progress':'New',now(),id)]);return json({ok:true});}
if(path.startsWith('/admin/')){if(user.role!=='admin')fail('Admin access required.',403);
if(path==='/admin/students'&&method==='GET'){const users=await all(db,'SELECT u.id,u.name,u.email,u.role,u.created_at,u.last_login,u.login_count,json_extract(d.data,\'$.course\') AS course FROM users u LEFT JOIN user_data d ON d.user_id=u.id ORDER BY u.created_at DESC LIMIT 2000');return json({students:users});}
if(path.match(/^\/admin\/students\/[^/]+\/logins$/)&&method==='GET')return json({logins:await all(db,'SELECT created_at FROM login_events WHERE user_id=? ORDER BY created_at DESC LIMIT 30',path.split('/')[3])});
if(path==='/admin/request-status'&&method==='POST'){const b=await body(request);if(!['New','In progress','Resolved'].includes(b.status))fail('Invalid status.');await run(db,'UPDATE requests SET status=?,updated_at=? WHERE id=?',b.status,now(),text(b.id,100,1));return json({ok:true});}
if(path==='/admin/content'&&method==='PUT'){const b=await body(request),kind=b.kind;if(!['course','video'].includes(kind))fail('Invalid content type.');const d=obj(b.data);const value={title:text(d.title,120,1),url:urlSafe(text(d.url,1500,1)),status:d.status==='Ready'?'Ready':'Draft'};const u=new URL(value.url);if(!['youtube.com','www.youtube.com','youtu.be'].includes(u.hostname))fail('Use a YouTube URL.');if(kind==='course'){if(u.pathname!=='/playlist'||!u.searchParams.get('list'))fail('Use a full playlist link.');Object.assign(value,{roadmap:text(d.roadmap,3000,1),subject:text(d.subject,120,1),baseCourse:text(d.baseCourse||'',80)});}else Object.assign(value,{topic:text(d.topic,100,1),language:text(d.language,30,1)});const id=b.id?text(b.id,100,1):crypto.randomUUID();await run(db,'INSERT INTO content(id,kind,data,updated_at) VALUES (?,?,?,?) ON CONFLICT(id) DO UPDATE SET kind=excluded.kind,data=excluded.data,updated_at=excluded.updated_at',id,kind,JSON.stringify(value),now());return json({id});}
if(path==='/admin/settings'&&method==='PUT'){const b=await body(request),channel=urlSafe(b.channel||'');if(channel){const u=new URL(channel);if(!['whatsapp.com','www.whatsapp.com','chat.whatsapp.com'].includes(u.hostname))fail('Use a WhatsApp channel or group URL.');}const value={channel,support:text(b.support,600,1)};await run(db,"INSERT INTO settings(id,data) VALUES ('campus',?) ON CONFLICT(id) DO UPDATE SET data=excluded.data",JSON.stringify(value));return json({ok:true});}}
fail('Not found.',404);
}catch(e){if(!e.status)console.error('Campus API error:',e.message);return json({error:e.status?e.message:'The server could not complete that action. Please try again.'},e.status||500);}}
