import http from 'node:http';
import { DatabaseSync } from 'node:sqlite';
import { readFile,writeFile,mkdir,unlink } from 'node:fs/promises';
import { readFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { Readable } from 'node:stream';
import { randomBytes } from 'node:crypto';
import { handleApi } from './api.mjs';
const root=path.dirname(path.dirname(fileURLToPath(import.meta.url)));
export function adapter(sqlite){return{prepare(sql){let args=[];return{bind(...values){args=values;return this;},async first(){return sqlite.prepare(sql).get(...args)||null;},async all(){return{results:sqlite.prepare(sql).all(...args)};},_runSync(){return{meta:sqlite.prepare(sql).run(...args)};},async run(){return this._runSync();}};},async batch(statements){sqlite.exec('BEGIN');try{const result=statements.map(s=>s._runSync());sqlite.exec('COMMIT');return result;}catch(e){sqlite.exec('ROLLBACK');throw e;}}};}
export async function startLocal(options={}){const dir=options.dir||path.join(root,'.campus-data');await mkdir(dir,{recursive:true});const sql=new DatabaseSync(path.join(dir,'campus.sqlite'));sql.exec(readFileSync(path.join(root,'server/schema.sql'),'utf8'));const uploads=path.join(dir,'uploads');await mkdir(uploads,{recursive:true});const env={DB:adapter(sql),ADMIN_SETUP_TOKEN:options.adminToken||process.env.ADMIN_SETUP_TOKEN||randomBytes(24).toString('hex'),BUCKET:{async put(key,data){const target=path.join(uploads,key);await mkdir(path.dirname(target),{recursive:true});await writeFile(target,Buffer.from(data));},async get(key){try{return{body:await readFile(path.join(uploads,key))};}catch{return null;}},async delete(key){await unlink(path.join(uploads,key)).catch(()=>{});}}};
const server=http.createServer(async(req,res)=>{try{const url=new URL(req.url,'http://'+(req.headers.host||'localhost'));if(url.pathname.startsWith('/api/')){const chunks=[];let size=0;for await(const chunk of req){size+=chunk.length;if(size>26*1024*1024){res.writeHead(413,{'Content-Type':'application/json'});res.end('{"error":"Request too large"}');return;}chunks.push(chunk);}const input=new Request(url,{method:req.method,headers:req.headers,...(!['GET','HEAD'].includes(req.method)?{body:Buffer.concat(chunks)}:{})});const result=await handleApi(input,env);res.writeHead(result.status,Object.fromEntries(result.headers));if(result.body)Readable.fromWeb(result.body).pipe(res);else res.end();return;}
let resource=decodeURIComponent(url.pathname);if(resource==='/'||resource.startsWith('/p/'))resource='/index.html';const file=path.resolve(root,'public','.'+resource);if(!file.startsWith(path.join(root,'public')+path.sep)){res.writeHead(403);res.end();return;}const content=await readFile(file);const type={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.svg':'image/svg+xml'}[path.extname(file)]||'application/octet-stream';res.writeHead(200,{'Content-Type':type,'X-Content-Type-Options':'nosniff','Referrer-Policy':'no-referrer','Cache-Control':'no-cache'});res.end(content);}catch{res.writeHead(404);res.end('Not found');}});
await new Promise((resolve,reject)=>{server.once('error',reject);server.listen(options.port??Number(process.env.PORT||4173),'127.0.0.1',resolve);});return{server,sql,env,url:`http://127.0.0.1:${server.address().port}`};}
if(process.argv[1]===fileURLToPath(import.meta.url)){const instance=await startLocal();console.log('Collexion Campus:',instance.url);console.log('Owner signup email: aryamangupta55@gmail.com');console.log('Private one-time owner setup code (do not share):',instance.env.ADMIN_SETUP_TOKEN);}
